<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeepIo.Shared\DeepIo.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Assets\OpenSans-Regular.ttf" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Assets\OFL-OpenSans.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
